[workspace]
members = ["derrick-core", "derrick-derive", "derrick-macros", "derrick-migrate"]
exclude = ["examples"]

[workspace.package]
version = "1.0.0-rc1"
edition = "2021"
authors = ["Daniel Donohue <daniel.donohue@beyondidentity.com>"]

[package]
name = "derrick"
description = "SQL migration tool inspired by refinery."
version.workspace = true
edition.workspace = true
authors.workspace = true

[workspace.dependencies]
derrick-core = { version = "=1.0.0-rc1", path = "derrick-core" }
derrick-derive = { version = "=1.0.0-rc1", path = "derrick-derive" }
derrick-macros = { version = "=1.0.0-rc1", path = "derrick-macros" }
derrick-migrate = { version = "=1.0.0-rc1", path = "derrick-migrate" }

[dependencies]
derrick-core.workspace = true
derrick-macros.workspace = true
derrick-migrate.workspace = true
