[package]
name = "derrick-derive"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
regex = "1.10"
syn = "2.0"
proc-macro2 = "1.0"