[package]
name = "derrick-derive"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
regex = "1.10.0"
syn = { version = "2.0", features = ["extra-traits"] }
proc-macro2 = "1.0"